version: "3"

x-basic-setting: &basic-setting
  init: true
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "2G"
      max-file: "2"
      compress: "true"
  healthcheck:
    test: [ "CMD-SHELL", "curl --fail http://localhost" ]
    interval: 30s
    timeout: 30s
    start_period: 10s
    retries: 3

volumes:
  pgsql_data:
    external: true

networks:
  pgsql:
    external: true

services:
  pgsql:
    <<: *basic-setting
    image: docker.io/library/postgres:13-alpine
    container_name: pgsql
    networks:
      - pgsql
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${ENV_PGSQL_USERNAME}
      - POSTGRES_PASSWORD=${ENV_PGSQL_PASSWORD}
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=${ENV_PGSQL_USERNAME}" ]
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 3
